name: macos

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  xcode:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ["12.5.1"]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3

      - name: Run CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel 10

      - uses: actions/upload-artifact@v3
        with:
          name: macos-xcode-${{ matrix.xcode }}
          path: |
            build/midikeys
            build/*/*.yml
          if-no-files-found: error
