name: windows

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Release]
        architecture: [x64]

    steps:
      - uses: actions/checkout@v3

      - name: Run CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 10

      - uses: actions/upload-artifact@v3
        with:
          name: midikeys-windows-x64
          path: |
            build/${{ matrix.build_type }}/*.exe
            build/*/*.yml
          if-no-files-found: error
